name: Generate PlantUML Diagrams
on: [push, pull_request]

jobs:
  plantuml:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Get changed UML files
        id: getfile
        run: |
          files=$(git diff --name-only HEAD^ HEAD | grep .puml | xargs)
          echo "files=$files" >> $GITHUB_OUTPUT
          if [ -n "$files" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate PNG Diagrams
        if: steps.getfile.outputs.changed == 'true'
        uses: holowinski/plantuml-github-action@1.2025.4
        with:
          args: -v -tpng docs/*.puml ${{steps.getfile.outputs.files}}

      - name: Push Local Changes
        if: steps.getfile.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate PNGs for PlantUML diagrams"
          branch: ${{ github.head_ref }}